workflows:
  android-workflow:
    name: Building for Android
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: main
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: npm i
      - name: Add Android platform
        script: |
          set -e # exit on first failed command
          ionic cordova platform remove android --nosave
          ionic cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android release
        script: |
          set -e # exit on first failed command
          cordova build android --no-interactive
    
    artifacts:
        - platforms/android/app/build/outputs/**/*.apk 
