workflows:
  android-workflow:
    name: Android workflow
    environment:
      xcode: 14.3.1
      node: 16.20.0
      npm: 8.19.4        
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci ci # equivalent of npm install for CI systems.
            # Requires package-lock.json or npm-shrinkwrap.json to be present
          cvm install 9.0.0
          cvm use 9.0.0
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android \
            --confirm \
            --no-interactive \
            --noresources
      - name: Build Android
        script: |
          set -x
          ionic cordova build android
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk