workflows:
  android-workflow:
    name: Android workflow
    environment:
      xcode: 14.3.1
      node: 16.20.0
      npm: 8.19.4        
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci ci # equivalent of npm install for CI systems.
            # Requires package-lock.json or npm-shrinkwrap.json to be present
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info        
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android \
            --confirm \
            --no-interactive \
            --noresources 
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk