workflows:
  android-workflow:
    name: Android workflow
    environment:
      xcode: 14.3.1
      node: 16.20.0
      npm: 8.19.4
      cordova: 12.0.0 
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cvm install 9.0.0
          cvm use 9.0.0
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android@11.0.0 \
            --confirm \
            --no-interactive
          ionic cordova prepare android
      - name: Build Android
        script: |
          set -x
          ionic cordova build android \
          --debug \
          --no-interactive \
          --device
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk