workflows:
  android-workflow:
    name: Building for Android
    environment:
      node: latest
    # triggering:
    #   events:
    #     - push
    #   branch_patterns: 
    #     - pattern: main
    #   cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: npm i
      - name: Build Android platform
        script: |
          set -e # exit on first failed command
          ionic cordova platform remove android --nosave
          ionic cordova build android --confirm --no-interactive --noresources
    
    artifacts:
        - platforms/android/app/build/outputs/**/*.apk 
